### ISSUE TITLE
Unknown file extension .ts

### ISSUE THREAD

**Issue by PortalRex** [PercentEquals/DiscordBot#1]
Running `npm run start` results in an unknown file extension error. Workaround is to use `node --loader ts-node/esm src/index.ts`. Unsure if my node is broken or not.

**Comment by Percent0** [comment]
Thanks for providing workaround. What node version do You have? Also check what ts-node version is when using `ts-node --version` inside bot dir.

**Comment by PortalRex** [comment]
Node version is `20.8.0`. Attempting to run ts-node throws a `Cannot find module 'arg'` error. I don't believe my version of ts-node is installed correctly.

**Comment by Percent0** [comment]
Bot is written on node 18, i have no idea if node 20 supports ts-node, might be worth trying to install it manually using:
```
npm install -g typescript
npm install -g ts-node
```

but if workaround works for You in node 20, then I might just add it as an alternative or default command.

**Comment by PortalRex** [comment]
It would appear I attempted to use node 16 instead of 18 originally.... Node 18 works fine. Thank you!
