### ISSUE TITLE
Automatic posting

### ISSUE THREAD

**Issue by PortalRex** [PercentEquals/DiscordBot#2]
Perhaps have a setting for the bot that looks for links and automatically posts the video/slideshow/etc.

**Comment by Percent0** [comment]
Hi! I like the idea, will probably add it soon.

**Comment by Percent0** [comment]
I was able to add this functionality. It will look for tiktok link in message and reply with attachment. If permissions are set up correctly it should also delete unnecessary embed from original message.

This functionality however will require MESSAGE CONTENT INTENT enabled for bot in discord developer portal.

Let me know if it what You had in mind!
